set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
  set_property IOSTANDARD LVCMOS33 [get_ports clk] 

set_property PACKAGE_PIN R2 [get_ports {reset}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {reset}] 
set_property PACKAGE_PIN C17 [get_ports psclk] 	 	 	 	 
    set_property IOSTANDARD LVCMOS33 [get_ports psclk] 
    set_property PULLUP true [get_ports psclk] 
set_property PACKAGE_PIN B17 [get_ports data]                      
    set_property IOSTANDARD LVCMOS33 [get_ports data]      
    set_property PULLUP true [get_ports data] 
         set_property PACKAGE_PIN V17 [get_ports {shoot_1}] 	 	 	 	 	 
              set_property IOSTANDARD LVCMOS33 [get_ports {shoot_1}]
                   set_property PACKAGE_PIN T18 [get_ports p1_u]  	 	 	 	 	 
                        set_property IOSTANDARD LVCMOS33 [get_ports p1_u] 
                   set_property PACKAGE_PIN W19 [get_ports p1_l]                           
                        set_property IOSTANDARD LVCMOS33 [get_ports p1_l] 
                   set_property PACKAGE_PIN T17 [get_ports p1_r]                           
                        set_property IOSTANDARD LVCMOS33 [get_ports p1_r] 
                   set_property PACKAGE_PIN U17 [get_ports p1_d]                           
                        set_property IOSTANDARD LVCMOS33 [get_ports p1_d] 
 	
 	set_property PACKAGE_PIN U16 [get_ports {led[0]}]  	 	 	 	 
          set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}] 
     set_property PACKAGE_PIN E19 [get_ports {led[1]}]                      
          set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}] 
     set_property PACKAGE_PIN U19 [get_ports {led[2]}]                      
          set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}] 
     set_property PACKAGE_PIN V19 [get_ports {led[3]}]                      
          set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}] 
          set_property PACKAGE_PIN W18 [get_ports {led[4]}]  	 	 	 	 
               set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}] 
          set_property PACKAGE_PIN U15 [get_ports {led[5]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}] 
          set_property PACKAGE_PIN U14 [get_ports {led[6]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}] 
          set_property PACKAGE_PIN V14 [get_ports {led[7]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}] 
          set_property PACKAGE_PIN V13 [get_ports {led[8]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}] 
          set_property PACKAGE_PIN V3 [get_ports {led[9]}]                          
               set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}] 
          set_property PACKAGE_PIN W3 [get_ports {led[10]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}] 
          set_property PACKAGE_PIN U3 [get_ports {led[11]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}] 
          set_property PACKAGE_PIN P3 [get_ports {led[12]}]                      
               set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}] 


set_property PACKAGE_PIN A15 [get_ports {rowin[0]}]  	 	 	 	 
                    set_property IOSTANDARD LVCMOS33 [get_ports {rowin[0]}] 
               ##Sch name = JB8 
               set_property PACKAGE_PIN A17 [get_ports {rowin[1]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {rowin[1]}] 
               ##Sch name = JB9 
               set_property PACKAGE_PIN C15 [get_ports {rowin[2]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {rowin[2]}] 
               ##Sch name = JB10  
               set_property PACKAGE_PIN C16 [get_ports {rowin[3]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {rowin[3]}] 
         
               ##Sch name = JB1 
           set_property PACKAGE_PIN A14 [get_ports {column[0]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {column[0]}] 
               ##Sch name = JB2 
              set_property PACKAGE_PIN A16 [get_ports {column[1]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {column[1]}] 
               ##Sch name = JB3 
               set_property PACKAGE_PIN B15 [get_ports {column[2]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {column[2]}] 
                    ##Sch name = JB4 
               set_property PACKAGE_PIN B16 [get_ports {column[3]}]                      
                    set_property IOSTANDARD LVCMOS33 [get_ports {column[3]}] 	
 	
 
set_property PACKAGE_PIN G19 [get_ports {red[0]}] 	 	 	 	 
   set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}] 
set_property PACKAGE_PIN H19 [get_ports {red[1]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}] 
set_property PACKAGE_PIN J19 [get_ports {red[2]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}] 
set_property PACKAGE_PIN N19 [get_ports {red[3]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}] 
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}] 
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]   
    set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]                    
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}] 
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]                     
   set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}] 
set_property PACKAGE_PIN J17 [get_ports {green[0]}]                 
   set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}] 
set_property PACKAGE_PIN H17 [get_ports {green[1]}]                 
   set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}] 
set_property PACKAGE_PIN G17 [get_ports {green[2]}]                 
  set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}] 
set_property PACKAGE_PIN D17 [get_ports {green[3]}]                 
  set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}] 
set_property PACKAGE_PIN P19 [get_ports hsync]                          
   set_property IOSTANDARD LVCMOS33 [get_ports hsync] 
set_property PACKAGE_PIN R19 [get_ports vsync]                          
  set_property IOSTANDARD LVCMOS33 [get_ports vsync] 
 